name: Project build
on: workflow_dispatch
jobs:
  helloworld:
    runs-on: windows-latest
    steps:
      - name: step1
        run: echo "Hello, world!!"

      - name: step2
        run: dotnet --info